INSERT INTO CUENTAS (numero_cuenta, PAZ_SALVO)
VALUES (1, 1);

INSERT INTO EMPLEADOS_GENERAL(TIPO_DOC, NUM_DOC, NOMBRE, HOTEL_NIT)
VALUES ('CC', 1234, 'JAIME', null);

INSERT INTO EMPLEADOS_GENERAL(TIPO_DOC, NUM_DOC, NOMBRE, HOTEL_NIT)
VALUES ('CC', 4321, 'RAUL', null);

/* IN RANGE < */
INSERT INTO CONSUMOS (ID, TOTAL, FECHA, CARGO_HABITACION, ID_SERVICIO, NUMERO_CUENTA, EMPLEADO_TIPO_DOC, EMPLEADO_NUM_DOC)
VALUES (1, 10, TO_TIMESTAMP ('01-01-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS'), null, null, 1, 'CC', '1234');

/* IN RANGE < */
INSERT INTO CONSUMOS (ID, TOTAL, FECHA, CARGO_HABITACION, ID_SERVICIO, NUMERO_CUENTA, EMPLEADO_TIPO_DOC, EMPLEADO_NUM_DOC)
VALUES (2, 20, TO_TIMESTAMP ('02-01-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS'), null, null, 1, 'CC', '1234');

/* DIFF CLIENT */
INSERT INTO CONSUMOS (ID, TOTAL, FECHA, CARGO_HABITACION, ID_SERVICIO, NUMERO_CUENTA, EMPLEADO_TIPO_DOC, EMPLEADO_NUM_DOC)
VALUES (3, 100, TO_TIMESTAMP ('02-01-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS'), null, null, null, 'CC', '1234');

/* OUT OF RANGE > */
INSERT INTO CONSUMOS (ID, TOTAL, FECHA, CARGO_HABITACION, ID_SERVICIO, NUMERO_CUENTA, EMPLEADO_TIPO_DOC, EMPLEADO_NUM_DOC)
VALUES (4, 30, TO_TIMESTAMP ('01-01-2023 12:00:00', 'DD-MM-YYYY HH:MI:SS'), null, null, 1, 'CC', '1234');

/* OUT OF RANGE < */
INSERT INTO CONSUMOS (ID, TOTAL, FECHA, CARGO_HABITACION, ID_SERVICIO, NUMERO_CUENTA, EMPLEADO_TIPO_DOC, EMPLEADO_NUM_DOC)
VALUES (5, 30, TO_TIMESTAMP ('01-01-2021 12:00:00', 'DD-MM-YYYY HH:MI:SS'), null, null, 1, 'CC', '1234');

/* IN RANGE < */
INSERT INTO CONSUMOS (ID, TOTAL, FECHA, CARGO_HABITACION, ID_SERVICIO, NUMERO_CUENTA, EMPLEADO_TIPO_DOC, EMPLEADO_NUM_DOC)
VALUES (6, 30, TO_TIMESTAMP ('03-01-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS'), null, null, 1, 'CC', '1234');

/* OTHER WORKER < */
INSERT INTO CONSUMOS (ID, TOTAL, FECHA, CARGO_HABITACION, ID_SERVICIO, NUMERO_CUENTA, EMPLEADO_TIPO_DOC, EMPLEADO_NUM_DOC)
VALUES (7, 120, TO_TIMESTAMP ('10-01-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS'), null, null, 1, 'CC', '4321');

INSERT INTO RESERVAS_HABITACIONES(ID, FECHA_ENTRADA, FECHA_SALIDA, NUM_PERSONAS, PLAN_PAGO, NUMERO_HABITACION, ID_SERVICIO_TIPO_HABITACION, RECEPCIONISTA_TIPO_DOC, RECEPCIONISTA_NUM_DOC, NUMERO_CUENTA)
VALUES (1, TO_TIMESTAMP ('01-01-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS'), TO_TIMESTAMP ('10-01-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS'), 1, 'PLANPAGO', 1, null, null, null, 1);

INSERT INTO RESERVAS_HABITACIONES(ID, FECHA_ENTRADA, FECHA_SALIDA, NUM_PERSONAS, PLAN_PAGO, NUMERO_HABITACION, ID_SERVICIO_TIPO_HABITACION, RECEPCIONISTA_TIPO_DOC, RECEPCIONISTA_NUM_DOC, NUMERO_CUENTA)
VALUES (2, TO_TIMESTAMP ('01-02-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS'), TO_TIMESTAMP ('31-12-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS'), 2, 'PLANPAGO', 2, null, null, null, 1);

INSERT INTO RESERVAS_HABITACIONES(ID, FECHA_ENTRADA, FECHA_SALIDA, NUM_PERSONAS, PLAN_PAGO, NUMERO_HABITACION, ID_SERVICIO_TIPO_HABITACION, RECEPCIONISTA_TIPO_DOC, RECEPCIONISTA_NUM_DOC, NUMERO_CUENTA)
VALUES (3, TO_TIMESTAMP ('01-03-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS'), TO_TIMESTAMP ('31-12-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS'), 2, 'PLANPAGO', 2, null, null, null, 1);

INSERT INTO RESERVAS_HABITACIONES(ID, FECHA_ENTRADA, FECHA_SALIDA, NUM_PERSONAS, PLAN_PAGO, NUMERO_HABITACION, ID_SERVICIO_TIPO_HABITACION, RECEPCIONISTA_TIPO_DOC, RECEPCIONISTA_NUM_DOC, NUMERO_CUENTA)
VALUES (4, TO_TIMESTAMP ('01-03-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS'), TO_TIMESTAMP ('10-04-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS'), 1, 'PLANPAGO', 1, null, null, null, 1);

INSERT INTO RESERVAS_HABITACIONES(ID, FECHA_ENTRADA, FECHA_SALIDA, NUM_PERSONAS, PLAN_PAGO, NUMERO_HABITACION, ID_SERVICIO_TIPO_HABITACION, RECEPCIONISTA_TIPO_DOC, RECEPCIONISTA_NUM_DOC, NUMERO_CUENTA)
VALUES (5, TO_TIMESTAMP ('01-01-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS'), TO_TIMESTAMP ('15-06-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS'), 3, 'PLANPAGO', 3, null, null, null, 1);

INSERT INTO CLIENTES_GENERAL(TIPO_DOC, NUM_DOC, NOMBRE)
VALUES ('CC',12345, 'ALEJO');

INSERT INTO RESERVAS_CLIENTES (CLIENTE_TIPO_DOC, CLIENTE_NUM_DOC, ID_RESERVA)
VALUES ('CC', 12345, 1);