/* ------------- */
/*      RFC 5    */
/* ------------- */
WITH CLIENTE AS (
    SELECT
        RESERVAS_HABITACIONES.NUMERO_CUENTA AS CUENTA
    FROM
        RESERVAS_HABITACIONES
        INNER JOIN RESERVAS_CLIENTES ON (
            RESERVAS_HABITACIONES.id = RESERVAS_CLIENTES.id_reserva
        )
    WHERE
        (RESERVAS_CLIENTES.cliente_num_doc = 12345)
)
SELECT
    SUM(CONSUMOS.TOTAL) AS TOTAL
FROM
    CONSUMOS
    INNER JOIN CLIENTE ON (CONSUMOS.NUMERO_CUENTA = CLIENTE.CUENTA)
WHERE
    (
        CONSUMOS.FECHA >= TO_TIMESTAMP('01-01-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS')
        AND CONSUMOS.FECHA <= TO_TIMESTAMP('31-12-2022 12:00:00', 'DD-MM-YYYY HH:MI:SS')
    );