/* ------------- */
/*      RFC 5    */
/* ------------- */
WITH CLIENTE AS (
    SELECT
        RESERVAS_HABITACIONES.NUMERO_CUENTA AS CUENTA
    FROM
        RESERVAS_HABITACIONES
        INNER JOIN RESERVAS_CLIENTES ON (
            RESERVAS_HABITACIONES.id = RESERVAS_CLIENTES.id_reserva
        )
    WHERE
        (RESERVAS_CLIENTES.cliente_num_doc = 12345)
)
SELECT
    SUM(CONSUMOS.TOTAL) AS TOTAL
FROM
    CONSUMOS
    INNER JOIN CLIENTE ON (CONSUMOS.NUMERO_CUENTA = CLIENTE.CUENTA)
WHERE
    (
        CONSUMOS.FECHA >= TO_TIMESTAMP('2022-01-01', 'YYYY-MM-DD')
        AND CONSUMOS.FECHA <= TO_TIMESTAMP('2022-12-31', 'YYYY-MM-DD')
    );